// Code generated by goctl. DO NOT EDIT.
// Source: auctionInfoManager.proto

package server

import (
	"context"

	"auction_server/auctionInfoManager-rpc/internal/logic"
	"auction_server/auctionInfoManager-rpc/internal/svc"
	"auction_server/auctionInfoManager-rpc/pb"
)

type AuctioninfomangercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuctioninfomangercenterServer
}

func NewAuctioninfomangercenterServer(svcCtx *svc.ServiceContext) *AuctioninfomangercenterServer {
	return &AuctioninfomangercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *AuctioninfomangercenterServer) GetUserPostInfo(ctx context.Context, in *pb.GetUserPostInfoReq) (*pb.GetUserPostInfoResp, error) {
	l := logic.NewGetUserPostInfoLogic(ctx, s.svcCtx)
	return l.GetUserPostInfo(in)
}

func (s *AuctioninfomangercenterServer) GetUserOfferInfo(ctx context.Context, in *pb.GetUserOfferInfoReq) (*pb.GetUserOfferInfoResp, error) {
	l := logic.NewGetUserOfferInfoLogic(ctx, s.svcCtx)
	return l.GetUserOfferInfo(in)
}

func (s *AuctioninfomangercenterServer) UserPostAuction(ctx context.Context, in *pb.UserPostAuctionReq) (*pb.UserPostAuctionResp, error) {
	l := logic.NewUserPostAuctionLogic(ctx, s.svcCtx)
	return l.UserPostAuction(in)
}

func (s *AuctioninfomangercenterServer) UserOfferAuction(ctx context.Context, in *pb.UserOfferAuctionReq) (*pb.UserOfferAuctionResp, error) {
	l := logic.NewUserOfferAuctionLogic(ctx, s.svcCtx)
	return l.UserOfferAuction(in)
}
