// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"auction_server/user-rpc/internal/logic"
	"auction_server/user-rpc/internal/svc"
	"auction_server/user-rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) UserRegister(ctx context.Context, in *pb.UserRegisterReq) (*pb.UserRegisterResp, error) {
	l := logic.NewUserRegisterLogic(ctx, s.svcCtx)
	return l.UserRegister(in)
}

func (s *UsercenterServer) UserLogin(ctx context.Context, in *pb.UserLoginReq) (*pb.UserLoginResp, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}

func (s *UsercenterServer) UserGetInfo(ctx context.Context, in *pb.UserGetInfoReq) (*pb.UserGetInfoResp, error) {
	l := logic.NewUserGetInfoLogic(ctx, s.svcCtx)
	return l.UserGetInfo(in)
}
