// Code generated by goctl. DO NOT EDIT.
package types

type AuctionPostReq struct {
	AuctionName  string `json:"auction_name"`
	PostUsername string `json:"post_username"`
	BasePrice    int    `json:"base_price"`
	Type         string `json:"type"`
}

type AuctionPostResp struct {
	Id           int    `json:"id"`
	Xid          string `json:"xid"`
	AuctionName  string `json:"auction_name"`
	PostUsername string `json:"post_username"`
	BasePrice    int    `json:"base_price"`
	Type         string `json:"type"`
}

type AuctionOfferReq struct {
	AuctionXid    string `json:"auction_xid"`
	OfferUsername string `json:"offer_username"`
	OfferPrice    int    `json:"offer_price"`
}

type AuctionOfferResp struct {
	Id            int    `json:"id"`
	Xid           string `json:"xid"`
	AuctionName   string `json:"auction_name"`
	PostUsername  string `json:"post_username"`
	OfferUsername string `json:"offer_username"`
	BasePrice     int    `json:"base_price"`
	CurrentPrice  int    `json:"current_price"`
	Type          string `json:"type"`
}
