// Code generated by goctl. DO NOT EDIT.
// Source: auction.proto

package auctioncenter

import (
	"context"

	"auction_server/auction-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuctionInfo           = pb.AuctionInfo
	AuctionOfferReq       = pb.AuctionOfferReq
	AuctionOfferResp      = pb.AuctionOfferResp
	AuctionPostReq        = pb.AuctionPostReq
	AuctionPostResp       = pb.AuctionPostResp
	GetAuctionInfoReq     = pb.GetAuctionInfoReq
	GetAuctionInfoResp    = pb.GetAuctionInfoResp
	GetAuctionsByTimeReq  = pb.GetAuctionsByTimeReq
	GetAuctionsByTimeResp = pb.GetAuctionsByTimeResp

	Auctioncenter interface {
		AuctionPost(ctx context.Context, in *AuctionPostReq, opts ...grpc.CallOption) (*AuctionPostResp, error)
		AuctionOffer(ctx context.Context, in *AuctionOfferReq, opts ...grpc.CallOption) (*AuctionOfferResp, error)
		GetAuctionInfo(ctx context.Context, in *GetAuctionInfoReq, opts ...grpc.CallOption) (*GetAuctionInfoResp, error)
		GetAuctionsByTime(ctx context.Context, in *GetAuctionsByTimeReq, opts ...grpc.CallOption) (*GetAuctionsByTimeResp, error)
	}

	defaultAuctioncenter struct {
		cli zrpc.Client
	}
)

func NewAuctioncenter(cli zrpc.Client) Auctioncenter {
	return &defaultAuctioncenter{
		cli: cli,
	}
}

func (m *defaultAuctioncenter) AuctionPost(ctx context.Context, in *AuctionPostReq, opts ...grpc.CallOption) (*AuctionPostResp, error) {
	client := pb.NewAuctioncenterClient(m.cli.Conn())
	return client.AuctionPost(ctx, in, opts...)
}

func (m *defaultAuctioncenter) AuctionOffer(ctx context.Context, in *AuctionOfferReq, opts ...grpc.CallOption) (*AuctionOfferResp, error) {
	client := pb.NewAuctioncenterClient(m.cli.Conn())
	return client.AuctionOffer(ctx, in, opts...)
}

func (m *defaultAuctioncenter) GetAuctionInfo(ctx context.Context, in *GetAuctionInfoReq, opts ...grpc.CallOption) (*GetAuctionInfoResp, error) {
	client := pb.NewAuctioncenterClient(m.cli.Conn())
	return client.GetAuctionInfo(ctx, in, opts...)
}

func (m *defaultAuctioncenter) GetAuctionsByTime(ctx context.Context, in *GetAuctionsByTimeReq, opts ...grpc.CallOption) (*GetAuctionsByTimeResp, error) {
	client := pb.NewAuctioncenterClient(m.cli.Conn())
	return client.GetAuctionsByTime(ctx, in, opts...)
}
