// Code generated by goctl. DO NOT EDIT.
// Source: infoManager.proto

package infomanagercenter

import (
	"context"

	"auction_server/infoManager-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuctionInfo          = pb.AuctionInfo
	GetUserOfferInfoReq  = pb.GetUserOfferInfoReq
	GetUserOfferInfoResp = pb.GetUserOfferInfoResp
	GetUserPostInfoReq   = pb.GetUserPostInfoReq
	GetUserPostInfoResp  = pb.GetUserPostInfoResp
	UserOfferAuctionReq  = pb.UserOfferAuctionReq
	UserOfferAuctionResp = pb.UserOfferAuctionResp
	UserPostAuctionReq   = pb.UserPostAuctionReq
	UserPostAuctionResp  = pb.UserPostAuctionResp

	Infomanagercenter interface {
		GetUserPostInfo(ctx context.Context, in *GetUserPostInfoReq, opts ...grpc.CallOption) (*GetUserPostInfoResp, error)
		GetUserOfferInfo(ctx context.Context, in *GetUserOfferInfoReq, opts ...grpc.CallOption) (*GetUserOfferInfoResp, error)
		UserPostAuction(ctx context.Context, in *UserPostAuctionReq, opts ...grpc.CallOption) (*UserPostAuctionResp, error)
		UserOfferAuction(ctx context.Context, in *UserOfferAuctionReq, opts ...grpc.CallOption) (*UserOfferAuctionResp, error)
	}

	defaultInfomanagercenter struct {
		cli zrpc.Client
	}
)

func NewInfomanagercenter(cli zrpc.Client) Infomanagercenter {
	return &defaultInfomanagercenter{
		cli: cli,
	}
}

func (m *defaultInfomanagercenter) GetUserPostInfo(ctx context.Context, in *GetUserPostInfoReq, opts ...grpc.CallOption) (*GetUserPostInfoResp, error) {
	client := pb.NewInfomanagercenterClient(m.cli.Conn())
	return client.GetUserPostInfo(ctx, in, opts...)
}

func (m *defaultInfomanagercenter) GetUserOfferInfo(ctx context.Context, in *GetUserOfferInfoReq, opts ...grpc.CallOption) (*GetUserOfferInfoResp, error) {
	client := pb.NewInfomanagercenterClient(m.cli.Conn())
	return client.GetUserOfferInfo(ctx, in, opts...)
}

func (m *defaultInfomanagercenter) UserPostAuction(ctx context.Context, in *UserPostAuctionReq, opts ...grpc.CallOption) (*UserPostAuctionResp, error) {
	client := pb.NewInfomanagercenterClient(m.cli.Conn())
	return client.UserPostAuction(ctx, in, opts...)
}

func (m *defaultInfomanagercenter) UserOfferAuction(ctx context.Context, in *UserOfferAuctionReq, opts ...grpc.CallOption) (*UserOfferAuctionResp, error) {
	client := pb.NewInfomanagercenterClient(m.cli.Conn())
	return client.UserOfferAuction(ctx, in, opts...)
}
