// Code generated by goctl. DO NOT EDIT.
// Source: infoManager.proto

package server

import (
	"context"

	"auction_server/infoManager-rpc/internal/logic"
	"auction_server/infoManager-rpc/internal/svc"
	"auction_server/infoManager-rpc/pb"
)

type InfomanagercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInfomanagercenterServer
}

func NewInfomanagercenterServer(svcCtx *svc.ServiceContext) *InfomanagercenterServer {
	return &InfomanagercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *InfomanagercenterServer) GetUserPostInfo(ctx context.Context, in *pb.GetUserPostInfoReq) (*pb.GetUserPostInfoResp, error) {
	l := logic.NewGetUserPostInfoLogic(ctx, s.svcCtx)
	return l.GetUserPostInfo(in)
}

func (s *InfomanagercenterServer) GetUserOfferInfo(ctx context.Context, in *pb.GetUserOfferInfoReq) (*pb.GetUserOfferInfoResp, error) {
	l := logic.NewGetUserOfferInfoLogic(ctx, s.svcCtx)
	return l.GetUserOfferInfo(in)
}

func (s *InfomanagercenterServer) UserPostAuction(ctx context.Context, in *pb.UserPostAuctionReq) (*pb.UserPostAuctionResp, error) {
	l := logic.NewUserPostAuctionLogic(ctx, s.svcCtx)
	return l.UserPostAuction(in)
}

func (s *InfomanagercenterServer) UserOfferAuction(ctx context.Context, in *pb.UserOfferAuctionReq) (*pb.UserOfferAuctionResp, error) {
	l := logic.NewUserOfferAuctionLogic(ctx, s.svcCtx)
	return l.UserOfferAuction(in)
}
