// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: auctionInfoManager.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuctionType int32

const (
	AuctionType_ArtWork    AuctionType = 0
	AuctionType_ArtsCrafts AuctionType = 1
	AuctionType_Jewelry    AuctionType = 2
	AuctionType_Home       AuctionType = 3
	AuctionType_Car        AuctionType = 4
	AuctionType_SmokeDrink AuctionType = 5
	AuctionType_Clothes    AuctionType = 6
	AuctionType_Others     AuctionType = 7
)

// Enum value maps for AuctionType.
var (
	AuctionType_name = map[int32]string{
		0: "ArtWork",
		1: "ArtsCrafts",
		2: "Jewelry",
		3: "Home",
		4: "Car",
		5: "SmokeDrink",
		6: "Clothes",
		7: "Others",
	}
	AuctionType_value = map[string]int32{
		"ArtWork":    0,
		"ArtsCrafts": 1,
		"Jewelry":    2,
		"Home":       3,
		"Car":        4,
		"SmokeDrink": 5,
		"Clothes":    6,
		"Others":     7,
	}
)

func (x AuctionType) Enum() *AuctionType {
	p := new(AuctionType)
	*p = x
	return p
}

func (x AuctionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionType) Descriptor() protoreflect.EnumDescriptor {
	return file_auctionInfoManager_proto_enumTypes[0].Descriptor()
}

func (AuctionType) Type() protoreflect.EnumType {
	return &file_auctionInfoManager_proto_enumTypes[0]
}

func (x AuctionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionType.Descriptor instead.
func (AuctionType) EnumDescriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{0}
}

type AuctionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuctionXid    string      `protobuf:"bytes,1,opt,name=auctionXid,proto3" json:"auctionXid,omitempty"`
	AuctionName   string      `protobuf:"bytes,2,opt,name=auctionName,proto3" json:"auctionName,omitempty"`
	AuctionImgUrl string      `protobuf:"bytes,3,opt,name=auctionImgUrl,proto3" json:"auctionImgUrl,omitempty"`
	BasePrice     int32       `protobuf:"varint,4,opt,name=basePrice,proto3" json:"basePrice,omitempty"`
	CurrentPrice  int32       `protobuf:"varint,5,opt,name=currentPrice,proto3" json:"currentPrice,omitempty"`
	PostUserXid   string      `protobuf:"bytes,6,opt,name=postUserXid,proto3" json:"postUserXid,omitempty"`
	OfferUserXid  string      `protobuf:"bytes,7,opt,name=offerUserXid,proto3" json:"offerUserXid,omitempty"`
	Type          AuctionType `protobuf:"varint,8,opt,name=type,proto3,enum=pb.AuctionType" json:"type,omitempty"`
}

func (x *AuctionInfo) Reset() {
	*x = AuctionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuctionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionInfo) ProtoMessage() {}

func (x *AuctionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionInfo.ProtoReflect.Descriptor instead.
func (*AuctionInfo) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionInfo) GetAuctionXid() string {
	if x != nil {
		return x.AuctionXid
	}
	return ""
}

func (x *AuctionInfo) GetAuctionName() string {
	if x != nil {
		return x.AuctionName
	}
	return ""
}

func (x *AuctionInfo) GetAuctionImgUrl() string {
	if x != nil {
		return x.AuctionImgUrl
	}
	return ""
}

func (x *AuctionInfo) GetBasePrice() int32 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *AuctionInfo) GetCurrentPrice() int32 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *AuctionInfo) GetPostUserXid() string {
	if x != nil {
		return x.PostUserXid
	}
	return ""
}

func (x *AuctionInfo) GetOfferUserXid() string {
	if x != nil {
		return x.OfferUserXid
	}
	return ""
}

func (x *AuctionInfo) GetType() AuctionType {
	if x != nil {
		return x.Type
	}
	return AuctionType_ArtWork
}

type GetUserPostInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserXid string `protobuf:"bytes,1,opt,name=userXid,proto3" json:"userXid,omitempty"`
}

func (x *GetUserPostInfoReq) Reset() {
	*x = GetUserPostInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPostInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPostInfoReq) ProtoMessage() {}

func (x *GetUserPostInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPostInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserPostInfoReq) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserPostInfoReq) GetUserXid() string {
	if x != nil {
		return x.UserXid
	}
	return ""
}

type GetUserPostInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auctions []*AuctionInfo `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
}

func (x *GetUserPostInfoResp) Reset() {
	*x = GetUserPostInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPostInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPostInfoResp) ProtoMessage() {}

func (x *GetUserPostInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPostInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserPostInfoResp) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPostInfoResp) GetAuctions() []*AuctionInfo {
	if x != nil {
		return x.Auctions
	}
	return nil
}

type GetUserOfferInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserXid string `protobuf:"bytes,1,opt,name=userXid,proto3" json:"userXid,omitempty"`
}

func (x *GetUserOfferInfoReq) Reset() {
	*x = GetUserOfferInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOfferInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOfferInfoReq) ProtoMessage() {}

func (x *GetUserOfferInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOfferInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserOfferInfoReq) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserOfferInfoReq) GetUserXid() string {
	if x != nil {
		return x.UserXid
	}
	return ""
}

type GetUserOfferInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auctions []*AuctionInfo `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
}

func (x *GetUserOfferInfoResp) Reset() {
	*x = GetUserOfferInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOfferInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOfferInfoResp) ProtoMessage() {}

func (x *GetUserOfferInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOfferInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserOfferInfoResp) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserOfferInfoResp) GetAuctions() []*AuctionInfo {
	if x != nil {
		return x.Auctions
	}
	return nil
}

type UserPostAuctionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserXid    string `protobuf:"bytes,1,opt,name=userXid,proto3" json:"userXid,omitempty"`
	AuctionXid string `protobuf:"bytes,2,opt,name=auctionXid,proto3" json:"auctionXid,omitempty"`
}

func (x *UserPostAuctionReq) Reset() {
	*x = UserPostAuctionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPostAuctionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostAuctionReq) ProtoMessage() {}

func (x *UserPostAuctionReq) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostAuctionReq.ProtoReflect.Descriptor instead.
func (*UserPostAuctionReq) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{5}
}

func (x *UserPostAuctionReq) GetUserXid() string {
	if x != nil {
		return x.UserXid
	}
	return ""
}

func (x *UserPostAuctionReq) GetAuctionXid() string {
	if x != nil {
		return x.AuctionXid
	}
	return ""
}

type UserPostAuctionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *UserPostAuctionResp) Reset() {
	*x = UserPostAuctionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPostAuctionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostAuctionResp) ProtoMessage() {}

func (x *UserPostAuctionResp) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostAuctionResp.ProtoReflect.Descriptor instead.
func (*UserPostAuctionResp) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{6}
}

func (x *UserPostAuctionResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type UserOfferAuctionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserXid    string `protobuf:"bytes,1,opt,name=userXid,proto3" json:"userXid,omitempty"`
	AuctionXid string `protobuf:"bytes,2,opt,name=auctionXid,proto3" json:"auctionXid,omitempty"`
}

func (x *UserOfferAuctionReq) Reset() {
	*x = UserOfferAuctionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfferAuctionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfferAuctionReq) ProtoMessage() {}

func (x *UserOfferAuctionReq) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfferAuctionReq.ProtoReflect.Descriptor instead.
func (*UserOfferAuctionReq) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{7}
}

func (x *UserOfferAuctionReq) GetUserXid() string {
	if x != nil {
		return x.UserXid
	}
	return ""
}

func (x *UserOfferAuctionReq) GetAuctionXid() string {
	if x != nil {
		return x.AuctionXid
	}
	return ""
}

type UserOfferAuctionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *UserOfferAuctionResp) Reset() {
	*x = UserOfferAuctionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auctionInfoManager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfferAuctionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfferAuctionResp) ProtoMessage() {}

func (x *UserOfferAuctionResp) ProtoReflect() protoreflect.Message {
	mi := &file_auctionInfoManager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfferAuctionResp.ProtoReflect.Descriptor instead.
func (*UserOfferAuctionResp) Descriptor() ([]byte, []int) {
	return file_auctionInfoManager_proto_rawDescGZIP(), []int{8}
}

func (x *UserOfferAuctionResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

var File_auctionInfoManager_proto protoreflect.FileDescriptor

var file_auctionInfoManager_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa2,
	0x02, 0x0a, 0x0b, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x69, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6d, 0x67, 0x55, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x6f, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x12, 0x23,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x58, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x58, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x08, 0x61, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x61,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2b, 0x0a, 0x08, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4e, 0x0a,
	0x12, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x69, 0x64, 0x22, 0x29, 0x0a,
	0x13, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x4f, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x58, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x58, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x14, 0x55, 0x73, 0x65,
	0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x2a, 0x73, 0x0a, 0x0b, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x10,
	0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x72, 0x74, 0x73, 0x43, 0x72, 0x61, 0x66, 0x74, 0x73, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4a, 0x65, 0x77, 0x65, 0x6c, 0x72, 0x79, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x48, 0x6f, 0x6d, 0x65, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x61, 0x72, 0x10,
	0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x6d, 0x6f, 0x6b, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x10,
	0x05, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x10, 0x06, 0x12, 0x0a,
	0x0a, 0x06, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x10, 0x07, 0x32, 0xaf, 0x02, 0x0a, 0x17, 0x61,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x66, 0x6f, 0x6d, 0x61, 0x6e, 0x67, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x42, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f,
	0x73, 0x74, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auctionInfoManager_proto_rawDescOnce sync.Once
	file_auctionInfoManager_proto_rawDescData = file_auctionInfoManager_proto_rawDesc
)

func file_auctionInfoManager_proto_rawDescGZIP() []byte {
	file_auctionInfoManager_proto_rawDescOnce.Do(func() {
		file_auctionInfoManager_proto_rawDescData = protoimpl.X.CompressGZIP(file_auctionInfoManager_proto_rawDescData)
	})
	return file_auctionInfoManager_proto_rawDescData
}

var file_auctionInfoManager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auctionInfoManager_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_auctionInfoManager_proto_goTypes = []interface{}{
	(AuctionType)(0),             // 0: pb.AuctionType
	(*AuctionInfo)(nil),          // 1: pb.AuctionInfo
	(*GetUserPostInfoReq)(nil),   // 2: pb.GetUserPostInfoReq
	(*GetUserPostInfoResp)(nil),  // 3: pb.GetUserPostInfoResp
	(*GetUserOfferInfoReq)(nil),  // 4: pb.GetUserOfferInfoReq
	(*GetUserOfferInfoResp)(nil), // 5: pb.GetUserOfferInfoResp
	(*UserPostAuctionReq)(nil),   // 6: pb.UserPostAuctionReq
	(*UserPostAuctionResp)(nil),  // 7: pb.UserPostAuctionResp
	(*UserOfferAuctionReq)(nil),  // 8: pb.UserOfferAuctionReq
	(*UserOfferAuctionResp)(nil), // 9: pb.UserOfferAuctionResp
}
var file_auctionInfoManager_proto_depIdxs = []int32{
	0, // 0: pb.AuctionInfo.type:type_name -> pb.AuctionType
	1, // 1: pb.GetUserPostInfoResp.auctions:type_name -> pb.AuctionInfo
	1, // 2: pb.GetUserOfferInfoResp.auctions:type_name -> pb.AuctionInfo
	2, // 3: pb.auctioninfomangercenter.GetUserPostInfo:input_type -> pb.GetUserPostInfoReq
	4, // 4: pb.auctioninfomangercenter.GetUserOfferInfo:input_type -> pb.GetUserOfferInfoReq
	6, // 5: pb.auctioninfomangercenter.UserPostAuction:input_type -> pb.UserPostAuctionReq
	8, // 6: pb.auctioninfomangercenter.UserOfferAuction:input_type -> pb.UserOfferAuctionReq
	3, // 7: pb.auctioninfomangercenter.GetUserPostInfo:output_type -> pb.GetUserPostInfoResp
	5, // 8: pb.auctioninfomangercenter.GetUserOfferInfo:output_type -> pb.GetUserOfferInfoResp
	7, // 9: pb.auctioninfomangercenter.UserPostAuction:output_type -> pb.UserPostAuctionResp
	9, // 10: pb.auctioninfomangercenter.UserOfferAuction:output_type -> pb.UserOfferAuctionResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auctionInfoManager_proto_init() }
func file_auctionInfoManager_proto_init() {
	if File_auctionInfoManager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auctionInfoManager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuctionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auctionInfoManager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPostInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auctionInfoManager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPostInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auctionInfoManager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOfferInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auctionInfoManager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOfferInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auctionInfoManager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPostAuctionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auctionInfoManager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPostAuctionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auctionInfoManager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfferAuctionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auctionInfoManager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfferAuctionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auctionInfoManager_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auctionInfoManager_proto_goTypes,
		DependencyIndexes: file_auctionInfoManager_proto_depIdxs,
		EnumInfos:         file_auctionInfoManager_proto_enumTypes,
		MessageInfos:      file_auctionInfoManager_proto_msgTypes,
	}.Build()
	File_auctionInfoManager_proto = out.File
	file_auctionInfoManager_proto_rawDesc = nil
	file_auctionInfoManager_proto_goTypes = nil
	file_auctionInfoManager_proto_depIdxs = nil
}
