// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: infoManager.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Infomanagercenter_GetUserPostInfo_FullMethodName  = "/pb.infomanagercenter/GetUserPostInfo"
	Infomanagercenter_GetUserOfferInfo_FullMethodName = "/pb.infomanagercenter/GetUserOfferInfo"
	Infomanagercenter_UserPostAuction_FullMethodName  = "/pb.infomanagercenter/UserPostAuction"
	Infomanagercenter_UserOfferAuction_FullMethodName = "/pb.infomanagercenter/UserOfferAuction"
)

// InfomanagercenterClient is the client API for Infomanagercenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfomanagercenterClient interface {
	GetUserPostInfo(ctx context.Context, in *GetUserPostInfoReq, opts ...grpc.CallOption) (*GetUserPostInfoResp, error)
	GetUserOfferInfo(ctx context.Context, in *GetUserOfferInfoReq, opts ...grpc.CallOption) (*GetUserOfferInfoResp, error)
	UserPostAuction(ctx context.Context, in *UserPostAuctionReq, opts ...grpc.CallOption) (*UserPostAuctionResp, error)
	UserOfferAuction(ctx context.Context, in *UserOfferAuctionReq, opts ...grpc.CallOption) (*UserOfferAuctionResp, error)
}

type infomanagercenterClient struct {
	cc grpc.ClientConnInterface
}

func NewInfomanagercenterClient(cc grpc.ClientConnInterface) InfomanagercenterClient {
	return &infomanagercenterClient{cc}
}

func (c *infomanagercenterClient) GetUserPostInfo(ctx context.Context, in *GetUserPostInfoReq, opts ...grpc.CallOption) (*GetUserPostInfoResp, error) {
	out := new(GetUserPostInfoResp)
	err := c.cc.Invoke(ctx, Infomanagercenter_GetUserPostInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infomanagercenterClient) GetUserOfferInfo(ctx context.Context, in *GetUserOfferInfoReq, opts ...grpc.CallOption) (*GetUserOfferInfoResp, error) {
	out := new(GetUserOfferInfoResp)
	err := c.cc.Invoke(ctx, Infomanagercenter_GetUserOfferInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infomanagercenterClient) UserPostAuction(ctx context.Context, in *UserPostAuctionReq, opts ...grpc.CallOption) (*UserPostAuctionResp, error) {
	out := new(UserPostAuctionResp)
	err := c.cc.Invoke(ctx, Infomanagercenter_UserPostAuction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infomanagercenterClient) UserOfferAuction(ctx context.Context, in *UserOfferAuctionReq, opts ...grpc.CallOption) (*UserOfferAuctionResp, error) {
	out := new(UserOfferAuctionResp)
	err := c.cc.Invoke(ctx, Infomanagercenter_UserOfferAuction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfomanagercenterServer is the server API for Infomanagercenter service.
// All implementations must embed UnimplementedInfomanagercenterServer
// for forward compatibility
type InfomanagercenterServer interface {
	GetUserPostInfo(context.Context, *GetUserPostInfoReq) (*GetUserPostInfoResp, error)
	GetUserOfferInfo(context.Context, *GetUserOfferInfoReq) (*GetUserOfferInfoResp, error)
	UserPostAuction(context.Context, *UserPostAuctionReq) (*UserPostAuctionResp, error)
	UserOfferAuction(context.Context, *UserOfferAuctionReq) (*UserOfferAuctionResp, error)
	mustEmbedUnimplementedInfomanagercenterServer()
}

// UnimplementedInfomanagercenterServer must be embedded to have forward compatible implementations.
type UnimplementedInfomanagercenterServer struct {
}

func (UnimplementedInfomanagercenterServer) GetUserPostInfo(context.Context, *GetUserPostInfoReq) (*GetUserPostInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPostInfo not implemented")
}
func (UnimplementedInfomanagercenterServer) GetUserOfferInfo(context.Context, *GetUserOfferInfoReq) (*GetUserOfferInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOfferInfo not implemented")
}
func (UnimplementedInfomanagercenterServer) UserPostAuction(context.Context, *UserPostAuctionReq) (*UserPostAuctionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserPostAuction not implemented")
}
func (UnimplementedInfomanagercenterServer) UserOfferAuction(context.Context, *UserOfferAuctionReq) (*UserOfferAuctionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOfferAuction not implemented")
}
func (UnimplementedInfomanagercenterServer) mustEmbedUnimplementedInfomanagercenterServer() {}

// UnsafeInfomanagercenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfomanagercenterServer will
// result in compilation errors.
type UnsafeInfomanagercenterServer interface {
	mustEmbedUnimplementedInfomanagercenterServer()
}

func RegisterInfomanagercenterServer(s grpc.ServiceRegistrar, srv InfomanagercenterServer) {
	s.RegisterService(&Infomanagercenter_ServiceDesc, srv)
}

func _Infomanagercenter_GetUserPostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPostInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfomanagercenterServer).GetUserPostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Infomanagercenter_GetUserPostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfomanagercenterServer).GetUserPostInfo(ctx, req.(*GetUserPostInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infomanagercenter_GetUserOfferInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOfferInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfomanagercenterServer).GetUserOfferInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Infomanagercenter_GetUserOfferInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfomanagercenterServer).GetUserOfferInfo(ctx, req.(*GetUserOfferInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infomanagercenter_UserPostAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPostAuctionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfomanagercenterServer).UserPostAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Infomanagercenter_UserPostAuction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfomanagercenterServer).UserPostAuction(ctx, req.(*UserPostAuctionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infomanagercenter_UserOfferAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOfferAuctionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfomanagercenterServer).UserOfferAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Infomanagercenter_UserOfferAuction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfomanagercenterServer).UserOfferAuction(ctx, req.(*UserOfferAuctionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Infomanagercenter_ServiceDesc is the grpc.ServiceDesc for Infomanagercenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Infomanagercenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.infomanagercenter",
	HandlerType: (*InfomanagercenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserPostInfo",
			Handler:    _Infomanagercenter_GetUserPostInfo_Handler,
		},
		{
			MethodName: "GetUserOfferInfo",
			Handler:    _Infomanagercenter_GetUserOfferInfo_Handler,
		},
		{
			MethodName: "UserPostAuction",
			Handler:    _Infomanagercenter_UserPostAuction_Handler,
		},
		{
			MethodName: "UserOfferAuction",
			Handler:    _Infomanagercenter_UserOfferAuction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infoManager.proto",
}
