// Code generated by goctl. DO NOT EDIT.
// Source: auction.proto

package server

import (
	"context"

	"auction_server/auction-rpc/internal/logic"
	"auction_server/auction-rpc/internal/svc"
	"auction_server/auction-rpc/pb"
)

type AuctioncenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuctioncenterServer
}

func NewAuctioncenterServer(svcCtx *svc.ServiceContext) *AuctioncenterServer {
	return &AuctioncenterServer{
		svcCtx: svcCtx,
	}
}

func (s *AuctioncenterServer) AuctionPost(ctx context.Context, in *pb.AuctionPostReq) (*pb.AuctionPostResp, error) {
	l := logic.NewAuctionPostLogic(ctx, s.svcCtx)
	return l.AuctionPost(in)
}

func (s *AuctioncenterServer) AuctionOffer(ctx context.Context, in *pb.AuctionOfferReq) (*pb.AuctionOfferResp, error) {
	l := logic.NewAuctionOfferLogic(ctx, s.svcCtx)
	return l.AuctionOffer(in)
}

func (s *AuctioncenterServer) GetAuctionInfo(ctx context.Context, in *pb.GetAuctionInfoReq) (*pb.GetAuctionInfoResp, error) {
	l := logic.NewGetAuctionInfoLogic(ctx, s.svcCtx)
	return l.GetAuctionInfo(in)
}

func (s *AuctioncenterServer) GetAuctionsByTime(ctx context.Context, in *pb.GetAuctionsByTimeReq) (*pb.GetAuctionsByTimeResp, error) {
	l := logic.NewGetAuctionsByTimeLogic(ctx, s.svcCtx)
	return l.GetAuctionsByTime(in)
}
