// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auction "auction_server/auction-api/internal/handler/auction"
	"auction_server/auction-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auction/post",
				Handler: auction.AuctionPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auction/offer",
				Handler: auction.AuctionOfferHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auction/auctions/time",
				Handler: auction.GetAuctionsByTimeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auction/v1"),
	)
}
