// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	img "auction_server/img-api/internal/handler/img"
	"auction_server/img-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/img/upload",
				Handler: img.ImgUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/img/show",
				Handler: img.ImgShowHandler(serverCtx),
			},
		},
		rest.WithPrefix("/img/v1"),
	)
}
