// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type UserRegisterResp struct {
	Flag        bool   `json:"flag"`
	Description string `json:"description"`
}

type UserLoginReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Id       int    `json:"id"`
	Xid      string `json:"xid"`
	UserName string `json:"user_name"`
}
